server:
  port: 8001
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.edu.lingnan.springcloud.pojo

spring:
  application:
    name: springcloud-provide-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

#eureka配置，注册到注册中心
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka/
  instance:
    instance-id: ${spring.application.name}-8001

info:
  app.name: shaosen-springcloud
  company.name: blog.shaosen.com

management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'