server:
  port: 81

#eureka配置，注册到注册中心
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}-81
spring:
  application:
    name: springcloud-consumer-dept