server:
  port: 9527

spring:
  application:
    name: springcloud-zuul-9527

eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
  client:
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka/

info:
  app.name: shaosen-springcloud
  company.name: blog.shaosen.com

zuul:
  routes:
    mydept.serviceId: springcloud-consumer-dept
    mydept.path: /mydept/**
  ignored-services: "*" #不能再使用这个路径访问，ignored
  prefix: /shaosen